# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azbt < Formula
  desc "TUI for managing Azure Bastion tunnels"
  homepage "https://github.com/chrisvfabio/az-bastion-tunnel"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chrisvfabio/az-bastion-tunnel/releases/download/v0.1.1/az-bastion-tunnel_darwin_amd64.tar.gz"
      sha256 "77c3dd5982de60bd3a97645f6b98991326b30bb2afeb9df229a9557fb0d0462d"

      define_method(:install) do
        bin.install "azbt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chrisvfabio/az-bastion-tunnel/releases/download/v0.1.1/az-bastion-tunnel_darwin_arm64.tar.gz"
      sha256 "2826b800afab473955a211769409c15f45975f528c3b1663f9b8de947971b8e4"

      define_method(:install) do
        bin.install "azbt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrisvfabio/az-bastion-tunnel/releases/download/v0.1.1/az-bastion-tunnel_linux_amd64.tar.gz"
      sha256 "822ca6a338a59fe9927ff8f1d9dab214c9c3bcb672baf069bc51362ffef70978"
      define_method(:install) do
        bin.install "azbt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrisvfabio/az-bastion-tunnel/releases/download/v0.1.1/az-bastion-tunnel_linux_arm64.tar.gz"
      sha256 "9761a0daae7ed288a91f3272a15918ceb4962850eb1c5d953e75cbaa6d4693e6"
      define_method(:install) do
        bin.install "azbt"
      end
    end
  end

  test do
    system "#{bin}/azbt --version"
  end
end
